{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) ( .Values.serviceMonitor.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "gar-exporter.name" .  }}
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  {{- end }}
  labels:
  {{- include "gar-exporter.labels" . | nindent 4 }}
  {{- if .Values.serviceMonitor.additionalLabels }}
  {{ toYaml .Values.serviceMonitor.additionalLabels | indent 4 }}
  {{- end }}
spec:
  endpoints:
    - targetPort: {{ .Values.service.port }}
      {{- if .Values.serviceMonitor.interval }}
      interval: {{ .Values.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.serviceMonitor.path }}
      path: {{ .Values.serviceMonitor.path }}
      {{- end }}
      {{- if .Values.serviceMonitor.timeout }}
      scrapeTimeout: {{ .Values.serviceMonitor.timeout }}
      honorLabels: {{ .Values.serviceMonitor.honorLabels }}
  {{- end }}
  jobLabel: {{ template "gar-exporter.fullname" . }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
  {{- include "gar-exporter.selectorLabels" . | nindent 6 }}
  {{- end }}
